// Widget 2 -- Entropy & Magic Byte Inspector (Module 2).
// Self-contained: no dependency on the shell store or any other widget.
// The Shannon entropy math here is real, computed live over synthetically
// generated byte buffers -- see entropySample below.
document.addEventListener('alpine:init', () => {
  Alpine.data('entropyInspector', () => ({
    entropyState: 'plaintext',
    entropyStates: [
      { id: 'plaintext', label: 'Plaintext DOCX', icon: 'file-text' },
      { id: 'zip', label: 'Compressed ZIP', icon: 'file-archive' },
      { id: 'encrypted', label: 'Encrypted target', icon: 'file-lock-2' },
      { id: 'intermittent', label: 'Intermittent encryption', icon: 'file-diff' },
    ],

    randHex(len) {
      const chars = '0123456789abcdef';
      let s = '';
      for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * 16)];
      return s;
    },

    shannonEntropy(bytes) {
      const freq = new Array(256).fill(0);
      for (let i = 0; i < bytes.length; i++) freq[bytes[i]]++;
      const len = bytes.length;
      let h = 0;
      for (let i = 0; i < 256; i++) {
        if (freq[i] === 0) continue;
        const p = freq[i] / len;
        h -= p * Math.log2(p);
      }
      return h;
    },

    plaintextPool: null,
    buildPlaintextPool() {
      // Rough English character-frequency weighting so simulated "plaintext" reads
      // like real prose (~4-4.5 bits/byte), not a flat/uniform distribution.
      const weights = { ' ': 18, e: 12, t: 9, a: 8, o: 7, i: 7, n: 7, s: 6, h: 6, r: 6, d: 4, l: 4, c: 3, u: 3, m: 3, w: 2, f: 2, g: 2, y: 2, p: 2, b: 1, ',': 1, '.': 1, v: 1, k: 1, T: 1, '\n': 1 };
      const pool = [];
      for (const ch in weights) for (let i = 0; i < weights[ch]; i++) pool.push(ch.charCodeAt(0));
      return pool;
    },
    genPlaintextBytes(n) {
      if (!this.plaintextPool) this.plaintextPool = this.buildPlaintextPool();
      const bytes = [];
      for (let i = 0; i < n; i++) bytes.push(this.plaintextPool[Math.floor(Math.random() * this.plaintextPool.length)]);
      return bytes;
    },

    genCompressedBytes(n) {
      const bytes = [];
      for (let i = 0; i < n; i++) {
        if (i > 0 && Math.random() < 0.06) { bytes.push(bytes[i - 1]); continue; }
        bytes.push((Math.floor(Math.random() * 200) + Math.floor(Math.random() * 56)) % 256);
      }
      return bytes;
    },

    genEncryptedBytes(n) {
      const bytes = [];
      for (let i = 0; i < n; i++) bytes.push(Math.floor(Math.random() * 256));
      return bytes;
    },

    genIntermittentBytes(n) {
      // Chunk size is deliberately wide (roughly 2 sliding-window widths — see
      // entropySample's windows=24 over n=4096) so the encrypt/skip stride
      // actually shows up as visible stripes rather than averaging out inside
      // every window.
      const bytes = [];
      const chunk = Math.max(16, Math.floor(n / 12));
      for (let i = 0; i < n; i++) {
        const encrypted = Math.floor(i / chunk) % 2 === 0; // header chunk (0) hit first, matches real-world targeting
        bytes.push(encrypted ? Math.floor(Math.random() * 256) : this.genPlaintextBytes(1)[0]);
      }
      return bytes;
    },

    hexDump(bytes) {
      const rows = [];
      for (let r = 0; r < 8; r++) {
        const start = r * 16;
        const rowBytes = bytes.slice(start, start + 16);
        if (!rowBytes.length) break;
        const hex = rowBytes.map(b => b.toString(16).padStart(2, '0')).join(' ');
        const ascii = rowBytes.map(b => (b >= 32 && b <= 126) ? String.fromCharCode(b) : '.').join('');
        rows.push({ offset: '0x' + start.toString(16).padStart(4, '0'), hex, ascii });
      }
      return rows;
    },

    get entropySample() {
      // Entropy is computed over a larger buffer than the hex view displays —
      // 128 bytes is too small a sample for empirical entropy to approach the
      // 8.0 ceiling even on truly random data (256 possible byte values need a
      // much bigger draw before the observed distribution looks uniform).
      const n = 4096;
      let bytes, magicHex, magicLabel, magicOk, flags;

      if (this.entropyState === 'plaintext') {
        bytes = this.genPlaintextBytes(n);
        bytes[0] = 0x50; bytes[1] = 0x4B; bytes[2] = 0x03; bytes[3] = 0x04;
        magicHex = '50 4B 03 04'; magicLabel = 'Recognized — Office Open XML / ZIP container'; magicOk = true;
        flags = [
          { level: 'ok', text: 'Magic bytes intact (50 4B 03 04)' },
          { level: 'ok', text: 'Entropy in expected range for a structured document' },
          { level: 'ok', text: 'Original extension preserved (.docx)' },
          { level: 'ok', text: 'No indicators of tampering' },
        ];
      } else if (this.entropyState === 'zip') {
        bytes = this.genCompressedBytes(n);
        bytes[0] = 0x1F; bytes[1] = 0x8B; bytes[2] = 0x08; bytes[3] = 0x00;
        magicHex = '1F 8B 08 00'; magicLabel = 'Recognized — gzip/deflate-style archive'; magicOk = true;
        flags = [
          { level: 'ok', text: 'Magic bytes intact' },
          { level: 'warn', text: 'Entropy already elevated due to compression — expected for this type' },
          { level: 'ok', text: 'Original extension preserved (.zip)' },
          { level: 'warn', text: 'High entropy alone is not itself a ransomware indicator — context matters' },
        ];
      } else if (this.entropyState === 'encrypted') {
        bytes = this.genEncryptedBytes(n);
        magicHex = [this.randHex(2), this.randHex(2), this.randHex(2), this.randHex(2)].join(' ').toUpperCase();
        magicLabel = 'No recognized signature — header overwritten with ciphertext'; magicOk = false;
        flags = [
          { level: 'danger', text: 'Magic bytes missing — header fully overwritten' },
          { level: 'danger', text: 'Entropy at ceiling — consistent with strong cipher output' },
          { level: 'danger', text: 'Extension appended (.dlock) — original type not inferable from name' },
          { level: 'warn', text: 'Cross-reference: ransom note artifacts present in same directory' },
        ];
      } else {
        bytes = this.genIntermittentBytes(n);
        magicHex = [this.randHex(2), this.randHex(2), this.randHex(2), this.randHex(2)].join(' ').toUpperCase();
        magicLabel = 'No recognized signature — header block encrypted'; magicOk = false;
        flags = [
          { level: 'danger', text: 'Magic bytes missing — header block encrypted' },
          { level: 'warn', text: 'Average entropy reads misleadingly moderate if sampled naively' },
          { level: 'warn', text: 'Sliding-window analysis reveals alternating high/low stripes' },
          { level: 'danger', text: 'Header-only scanning under-detects this file — scan the full length' },
        ];
      }

      const entropy = this.shannonEntropy(bytes);
      const result = { hexRows: this.hexDump(bytes.slice(0, 128)), entropy, magicHex, magicLabel, magicOk, flags };

      if (this.entropyState === 'intermittent') {
        const windows = 24;
        const winSize = Math.max(1, Math.floor(bytes.length / windows));
        const strip = [];
        for (let w = 0; w < windows; w++) {
          const seg = bytes.slice(w * winSize, w * winSize + winSize);
          if (!seg.length) continue;
          const e = this.shannonEntropy(seg);
          const t = Math.max(0, Math.min(1, e / 8));
          const r = Math.round(244 * t + 16 * (1 - t));
          const g = Math.round(63 * t + 185 * (1 - t));
          const b = Math.round(94 * t + 129 * (1 - t));
          strip.push({ value: e, color: `rgba(${r},${g},${b},${(0.55 + t * 0.45).toFixed(2)})` });
        }
        result.windowStrip = strip;
      }
      return result;
    },
  }));
});
